BLAZEDEMO_LOGIN_URL=https://blazedemo.com/login
BLAZEDEMO_LOGIN_URL_ENDPOINT=/login
BLAZEDEMO_LOGIN_TEXT=BlazeDemo
BLAZEDEMO_LOGIN_SECOND_TEXT=Login
BLAZEDEMO_LOGIN_EMAIL_ADDRESS=random@random.com
BLAZEDEMO_LOGIN_PASSWORD=testAdmin123
BLAZEDEMO_LOGIN_EMAIL_ADDRESS_RANDOM_CHARACTERS=##$$$#%#^%^%^^%^%#^#%
BLAZEDEMO_LOGIN_PASSWORD_RANDOM_CHARACTERS=#%@%#%###^%#%####%$%#$%