name: Testing from production environment


on:
    push:
        branches: [main]
        
    pull_request:
        branches: [main]

jobs:
    changes:
        runs-on: ubuntu-latest
        outputs:
            playwright: ${{ steps.filter.outputs.playwright }}
        steps:
            - uses: actions/checkout@v4
            - uses: dorny/paths-filter@v3
              id: filter
              with:
                filters: |
                    playwright:
                        - 'production/**'
                        - 'playwright.config.js'
#                        - 'production/mock_api_tests/**'
#                        - 'production/regression/**'
#                        - 'production/sanity/**'
#                        - 'production/smoke/**'
                        
    
    test:
        needs: changes
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: npm ci

            - name: Run Playwright tests in production environment for testing mock apis
              if: needs.changes.outputs.playwright == 'true'
              run: npx playwright test tests/Production/Mock_Api_Tests/api_test.spec.js --testMatch="**/*.js"
            
            - name: Run Playwright tests in production environment to test edge case test cases in sanity test suite
              if: needs.changes.outputs.playwright == 'true'
              run: npx playwright test tests/Production/Regression/edge_case_tests --testMatch="**/*.js"
            
            - name: Run Playwright tests in production environment for testing flight purchase verification in regression test suite
              if: needs.changes.outputs.playwright == 'true'
              run: npx playwright test tests/Production/Regression/flight_purchase_verification.spec.js --testMatch="**/*.js"
            
            - name: Run Playwright tests in production environment for testing login application in regression test suite
              if: needs.changes.outputs.playwright == 'true'
              run: npx playwright test tests/Production/Regression/login.spec.js --testMatch="**/*.js"

            - name: Run Playwright tests in production environment for testing departure and destination menu for each city in regression test suite
              if: needs.changes.outputs.playwright == 'true'
              run: npx playwright test tests/Production/Regression/menu_departure_destination_city.spec.js --testMatch="**/*.js"
              
            - name: Run Playwright tests in production environment for testing register form in regression test suite
              if: needs.changes.outputs.playwright == 'true'
              run: npx playwright test tests/Production/Regression/register.spec.js --testMatch="**/*.js"
            
            - name: Run Playwright tests in production environment to test edge case test cases in sanity test suite
              if: needs.changes.outputs.playwright == 'true'
              run: npx playwright test tests/Production/Sanity/edge_case_tests --testMatch="**/*.js"

            - name: Run Playwright tests in production environment for testing flight purchase verification in regression test suite
              if: needs.changes.outputs.playwright == 'true'
              run: npx playwright test tests/Production/Sanity/flight_purchase_verification.spec.js --testMatch="**/*.js"
            
            - name: Run Playwright tests in production environment for testing login application in regression test suite
              if: needs.changes.outputs.playwright == 'true'
              run: npx playwright test tests/Production/Sanity/login.spec.js --testMatch="**/*.js"

            - name: Run Playwright tests in production environment for testing departure and destination menu for each city in regression test suite
              if: needs.changes.outputs.playwright == 'true'
              run: npx playwright test tests/Production/Sanity/menu_departure_destination_city.spec.js --testMatch="**/*.js"
              
            - name: Run Playwright tests in production environment for testing register form in regression test suite
              if: needs.changes.outputs.playwright == 'true'
              run: npx playwright test tests/Production/Sanity/register.spec.js --testMatch="**/*.js"

            - name: No-op success
              if: needs.changes.outputs.playwright == 'false'
              run: echo "No playwright changes detected"


#on:
#    push:
#        branches: 
#            - main
#        paths:
#            - 'production/**'
#            - 'playwright.config.js'
#            - '/tests/production/mock_api_tests/**'
#            - '/test/production/regression/**'
#            - '/test/production/sanity/**'
#    pull_request:
#        branches: 
#            - main
#        paths:
#            - 'production/**'
#            - 'playwright.config.js'
#            - '/tests/production/mock_api_tests/**'
#            - '/tests/production/regression/**'
#            - '/tests/production/sanity/**'

#jobs:
#    run_tests:
#        runs-on: ubuntu
#        strategy:
#            matrix:
#                project-dir: [./tests/production/mock_api_tests/, ./tests/production/regression/, ./tests/production/sanity/]
#        defaults:
#            run:
#                working-directory: ${{matrix.project-dir}
#                 working-directory: './production'
#        steps:
#            - name: Checkout repository code
#              uses: actions/checkout@v4
#            - name: Setup Node.js
#              uses: actions/setup-node@v4
#              with:
#                node-version: '24'
            
#            - name: Install dependencies
#              run: npm ci
#            - name: Execute specific-folder tests
#              run: npm test
              
        

