name: Testing from production environment


on:
    pull_request:
        branches:
            - 'main'

jobs:
    changes:
        runs-on: ubuntu
        outputs:
            playwright: ${{ steps.filter.outputs.playwright }}
        steps:
            - uses: actions/checkout@v4
            - uses: dorny/paths-filter@v4
              id: filter
              with:
                filters: |
                    playwright:
                        - '/production/**'
                        - 'playwright.config.js'
    
    test:
        needs: changes
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              if: needs.changes.outputs.playwright == 'true'
              run: npm ci
            
            - name: Run Playwright tests
              if: needs.changes.outputs.playwright == 'true'
              run: npx playwright test

            - name: No-op success
              if: needs.changes.outputs.playwright == 'false'
              run: echo "No playwright changes detected"


#on:
#    push:
#        branches: 
#            - main
#        paths:
#            - 'production/**'
#            - 'playwright.config.js'
#            - '/tests/production/mock_api_tests/**'
#            - '/test/production/regression/**'
#            - '/test/production/sanity/**'
#    pull_request:
#        branches: 
#            - main
#        paths:
#            - 'production/**'
#            - 'playwright.config.js'
#            - '/tests/production/mock_api_tests/**'
#            - '/tests/production/regression/**'
#            - '/tests/production/sanity/**'

#jobs:
#    run_tests:
#        runs-on: ubuntu
#        strategy:
#            matrix:
#                project-dir: [./tests/production/mock_api_tests/, ./tests/production/regression/, ./tests/production/sanity/]
#        defaults:
#            run:
#                working-directory: ${{matrix.project-dir}
#                 working-directory: './production'
#        steps:
#            - name: Checkout repository code
#              uses: actions/checkout@v4
#            - name: Setup Node.js
#              uses: actions/setup-node@v4
#              with:
#                node-version: '24'
            
#            - name: Install dependencies
#              run: npm ci
#            - name: Execute specific-folder tests
#              run: npm test
              
        

