name: Testing from live environment

on:
    push:
        branches: [main]
         
    pull_request:
        branches: [main]

jobs:
    # Stage 1. Check what changed
    changes:
        runs-on: ubuntu-latest
        outputs:
            playwright: ${{steps.filter.outputs.playwright}}
        steps:
            - uses: actions/checkout@v4
            - uses: dorny/paths-filter@v4
              id: filter
              with:
                filters: |
                    playwright:
                        - 'live/**'
                        - 'playwright.config.js'
#                        - 'live/mock_api_tests/**'
#                        - 'live/regression/**'
#                        - 'live/sanity/**'
#                        - 'live/smoke/**'
                      
    
    # Stage 2. Run tests conditionally
    test:
        needs: changes
        # Always runs its block, but skips if no changes occured
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: npm ci

            - name: Run Playwright tests in live environment for testing mock apis
              if: needs.changes.outputs.playwright == 'true'
              run: npx playwright test tests/Live/Mock_Api_Tests/api_test.spec.js --test-match="*api_test.spec.js"
            
            - name: Run Playwright tests in live environment to test edge case test cases in sanity test suite
              if: needs.changes.outputs.playwright == 'true'
              run: npx playwright test tests/Live/Regression/Edge_Case_Tests/
            
            - name: Run Playwright tests in live environment for testing flight purchase verification in regression test suite
              if: needs.changes.outputs.playwright == 'true'
              run: npx playwright test tests/Live/Regression/flight_purchase_verification.spec.js --test-match="*flight_purchase_verification.spec.js"
            
            - name: Run Playwright tests in live environment for testing login application in regression test suite
              if: needs.changes.outputs.playwright == 'true'
              run: npx playwright test tests/Live/Regression/login.spec.js --test-match="*login.spec.js"
 
            - name: Run Playwright tests in live environment for testing departure and destination menu for each city in regression test suite
              if: needs.changes.outputs.playwright == 'true'
              run: npx playwright test tests/Live/Regression/menu_departure_destination_city.spec.js --test-match="*menu_departure_destination_city.spec.js"
              
            - name: Run Playwright tests in live environment for testing register form in regression test suite
              if: needs.changes.outputs.playwright == 'true'
              run: npx playwright test tests/Live/Regression/register.spec.js --test-match="*register.spec.js"
            
            - name: Run Playwright tests in live environment to test edge case test cases in sanity test suite
              if: needs.changes.outputs.playwright == 'true'
              run: npx playwright test tests/Live/Sanity/Edge_Case_Tests/

            - name: Run Playwright tests in live environment for testing flight purchase verification in regression test suite
              if: needs.changes.outputs.playwright == 'true'
              run: npx playwright test tests/Live/Sanity/flight_purchase_verification.spec.js --test-match="*flight_purchase_verification.spec.js"
            
            - name: Run Playwright tests in live environment for testing login application in regression test suite
              if: needs.changes.outputs.playwright == 'true'
              run: npx playwright test tests/Live/Sanity/login.spec.js --test-match="*login.spec.js"

            - name: Run Playwright tests in live environment for testing departure and destination menu for each city in regression test suite
              if: needs.changes.outputs.playwright == 'true'
              run: npx playwright test tests/Live/Sanity/menu_departure_destination_city.spec.js --test-match="*menu_departure_destination_city.spec.js"
              
            - name: Run Playwright tests in live environment for testing register form in regression test suite
              if: needs.changes.outputs.playwright == 'true'
              run: npx playwright test tests/Live/Sanity/register.spec.js --test-match="*register.spec.js"

            # If no changes occur
            - name: No-op Success
              if: needs.changes.outputs.playwright == 'false'
              run: echo "No playwright changes detected. Skipping test safely"
#on:
#    push:
#        branches: 
#            - main
#        paths:
#            - '/live/**'
#            - 'playwright.config.js'
#            - '/tests/live/mock_api_tests/**'
#            - '/tests/live/regression/**'
#            - '/tests/live/sanity/**'

#    pull_request:
#        branches: 
#            - main
#        paths:
#            - '/live/**'
#            - 'playwright.config.js'
#            - '/tests/live/mock_api_tests/**'
#            - '/tests/live/regression/**'
#            - '/tests/live/sanity/**'

#jobs:
#    run_tests:
#        runs-on: ubuntu
#        strategy:
#            matrix:
#                project-dir: [./tests/live/mock_api_tests/, ./tests/live/regression/, ./tests/live/sanity/]
        
#        defaults:
#            run:
#                working-directory: ${{matrix.project-dir}
#                 working-directory: './live'
#        steps:
#            - name: Checkout repository code
#              uses: actions/checkout@v4
#            - name: Setup node.js
#              uses: actions/setup-node@v4
#              with:
#                node-version: '24'
#            
#            - name: Install dependencies
#              run: npm ci
#            - name: Execute specific-folder tests
#              run: npm test

